# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

fos_ck_editor:
    configs:
        my_config:
#            toolbar: [ ["Source", "-", "Cut","Copy","Paste","Pastetext"] ]
            toolbar: [
                ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo' ],
                [ 'Bold', 'Italic', 'Underline', 'Strike', '-', 'Subscript', 'Superscript', '-', 'BulletedList', 'NumberedList'],
                ['JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'Link', 'Unlink'],
                '/',
                ['Image', 'Table', 'HorizontalRule' , 'SpecialChar', '-'],
                ['Styles', 'Format', 'Font', 'FontSize', 'FontColor', 'BGColor', '-', 'Maximize'],
                ['Source', 'Preview' ]
            ]
            width: 200%